### ISSUE TITLE
Fix taint unit test for x86-64

### ISSUE THREAD

**Issue by tnballo** [panda-re/panda_test#4]
The [GitHub Actions CI](https://github.com/panda-re/panda/blob/master/.github/workflows/parallel_taint_unit.yml) runs all taint unit tests for `i386`, but same set of tests don't run all run for `x86-64`. The binaries are compiled for x64 and executed in-guest, and a log file is produced, but the log file contents are a subset of those produced by the `i386` tests.

The issue could be with the [x64 hypercall implementation](https://github.com/panda-re/panda_test/blob/master/taint_include/taint.h), which is the mechanism by which invariants are "asserted" (guest triggers write to log, funtions with "assert" in the name don't actually change execution so that they can be used on replays).

**Comment by MarkMankins** [comment]
I think this one is resolved now?  @AndrewFasano ?

**Comment by AndrewFasano** [comment]
Yeah, we fixed a bug in the panda_test repo (https://github.com/panda-re/panda_test/commit/c17f6a2abe8cc39359c4caccf0fbf5f78b3ec070) so now the x86_64 taint tests are running.

Edit: 🤦‍♂️ just realized that this is the panda_test repo.
